openapi: 3.0.0
info:
  title: Bracket
  description: API supporting tournament brackets
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Production Server
  - url: http://staging-api.example.com
    description: Test Server
paths:
  /brackets:
    get:
      tags:
        - Brackets
      summary: Gets all brackets.
      description: >
        It grabs all available brackets
      operationId: getBrackets
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bracket"
components:
  schemas:
    bracket:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
          final:
            type: string
          matches:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                home:
                  type: string
                away:
                  type: string