openapi: 3.0.0
info:
  title: Bracket
  description: API supporting tournament brackets
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Production Server
  - url: http://staging-api.example.com
    description: Test Server
paths:
  /brackets/{id}:
    get:
      tags:
        - Brackets
      summary: Gets a bracket by ID.
      description: >
        It grabs a spot in time bracket detail
      operationId: getBracketById
      parameters:
        - name: id
          in: path
          description: Bracket ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bracket"
components:
  schemas:
    bracket:
      type: array
      items:
        type: object
        properties:
          id:
            type: integer
            format: int64
          final:
            type: string
          matches:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                  format: int64
                home:
                  type: string
                away:
                  type: string